-- MySQL Script generated by MySQL Workbench
-- Fri Nov 22 15:56:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aesthetic_gallery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aesthetic_gallery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aesthetic_gallery` DEFAULT CHARACTER SET utf8mb4 ;
USE `aesthetic_gallery` ;

-- -----------------------------------------------------
-- Table `aesthetic_gallery`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aesthetic_gallery`.`admin` (
  `Id_Admin` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(320) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `tel` VARCHAR(45) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `aesthetic_gallery`.`style`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aesthetic_gallery`.`style` (
  `Id_style` INT NOT NULL AUTO_INCREMENT,
  `style` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`Id_style`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `aesthetic_gallery`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aesthetic_gallery`.`user` (
  `Id_user` INT NOT NULL AUTO_INCREMENT,
  `user_type` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Pseudo` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(320) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `date_naissance` DATE NULL,
  `consent` TINYINT(1) NOT NULL,
  `tel` VARCHAR(20) NULL,
  `Login_token` VARCHAR(100) NULL,
  `date_creation` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `style_Id_style` INT NOT NULL,
  PRIMARY KEY (`Id_user`),
  INDEX `fk_artiste_style1_idx` (`style_Id_style` ASC) VISIBLE,
  CONSTRAINT `fk_artiste_style1`
    FOREIGN KEY (`style_Id_style`)
    REFERENCES `aesthetic_gallery`.`style` (`Id_style`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `aesthetic_gallery`.`art_piece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aesthetic_gallery`.`art_piece` (
  `Id_Art` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `prix` DECIMAL NOT NULL,
  `mode_vente` VARCHAR(15) NOT NULL,
  `offre` DECIMAL NULL,
  `date_creation` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `artiste_Id_Artiste` INT NOT NULL,
  PRIMARY KEY (`Id_Art`),
  INDEX `fk_art_piece_artiste_idx` (`artiste_Id_Artiste` ASC) VISIBLE,
  CONSTRAINT `fk_art_piece_artiste`
    FOREIGN KEY (`artiste_Id_Artiste`)
    REFERENCES `aesthetic_gallery`.`user` (`Id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `aesthetic_gallery`.`cgu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aesthetic_gallery`.`cgu` (
  `Id_cgu` INT NOT NULL AUTO_INCREMENT,
  `condition` TEXT NOT NULL,
  PRIMARY KEY (`Id_cgu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `aesthetic_gallery`.`faq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aesthetic_gallery`.`faq` (
  `Id_FAQ` INT NOT NULL AUTO_INCREMENT,
  `questions` TEXT NOT NULL,
  `reponses` TEXT NOT NULL,
  PRIMARY KEY (`Id_FAQ`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `aesthetic_gallery`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aesthetic_gallery`.`image` (
  `Id_image` INT(11) NOT NULL AUTO_INCREMENT,
  `chemin_acces` INT(11) NOT NULL,
  `artiste_Id_Artiste` INT NOT NULL,
  PRIMARY KEY (`Id_image`),
  INDEX `fk_image_artiste1_idx` (`artiste_Id_Artiste` ASC) VISIBLE,
  CONSTRAINT `fk_image_artiste1`
    FOREIGN KEY (`artiste_Id_Artiste`)
    REFERENCES `aesthetic_gallery`.`user` (`Id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `aesthetic_gallery`.`sujet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aesthetic_gallery`.`sujet` (
  `Id_sujet` INT(11) NOT NULL AUTO_INCREMENT,
  `objet_nom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id_sujet`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `aesthetic_gallery`.`artiste_has_sujet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aesthetic_gallery`.`artiste_has_sujet` (
  `artiste_Id_Artiste` INT NOT NULL,
  `sujet_Id_sujet` INT(11) NOT NULL,
  PRIMARY KEY (`artiste_Id_Artiste`, `sujet_Id_sujet`),
  INDEX `fk_artiste_has_sujet_sujet1_idx` (`sujet_Id_sujet` ASC) VISIBLE,
  INDEX `fk_artiste_has_sujet_artiste1_idx` (`artiste_Id_Artiste` ASC) VISIBLE,
  CONSTRAINT `fk_artiste_has_sujet_artiste1`
    FOREIGN KEY (`artiste_Id_Artiste`)
    REFERENCES `aesthetic_gallery`.`user` (`Id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artiste_has_sujet_sujet1`
    FOREIGN KEY (`sujet_Id_sujet`)
    REFERENCES `aesthetic_gallery`.`sujet` (`Id_sujet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
